package com.telcobright.scheduler.examples;

import com.telcobright.core.annotation.*;
import com.telcobright.scheduler.SchedulableEntity;

import java.time.LocalDateTime;
import java.util.UUID;

@Table(name = "sms_retry_schedules")
public class SmsRetryEntity implements SchedulableEntity {

    @Id(autoGenerated = false)
    @Column(name = "id")
    private String id;

    @ShardingKey
    @Column(name = "retry_time")
    private LocalDateTime retryTime;

    @Column(name = "phone_number")
    private String phoneNumber;

    @Column(name = "message")
    private String message;

    @Column(name = "retry_count")
    private Integer retryCount;

    @Column(name = "max_retries")
    private Integer maxRetries;

    @Column(name = "status")
    private String status;

    @Column(name = "scheduled")
    private Boolean scheduled;

    @Column(name = "original_scheduled_time")
    private LocalDateTime originalScheduledTime;

    @Column(name = "last_error")
    private String lastError;

    public SmsRetryEntity() {}

    public SmsRetryEntity(String phoneNumber, String message, LocalDateTime retryTime, Integer maxRetries) {
        this.id = UUID.randomUUID().toString();
        this.phoneNumber = phoneNumber;
        this.message = message;
        this.retryTime = retryTime;
        this.originalScheduledTime = retryTime;
        this.retryCount = 0;
        this.maxRetries = maxRetries;
        this.status = "PENDING";
        this.scheduled = false;
    }

    // ShardingEntity interface methods
    @Override
    public String getId() {
        return id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    @Override
    public LocalDateTime getPartitionColValue() {
        return retryTime;
    }

    @Override
    public void setPartitionColValue(LocalDateTime value) {
        this.retryTime = value;
    }

    // SchedulableEntity interface methods
    @Override
    public LocalDateTime getScheduledTime() {
        return retryTime;
    }

    public void setRetryTime(LocalDateTime retryTime) {
        this.retryTime = retryTime;
    }

    @Override
    public Boolean getScheduled() {
        return scheduled;
    }

    @Override
    public void setScheduled(Boolean scheduled) {
        this.scheduled = scheduled;
    }

    @Override
    public String getJobId() {
        return "sms-retry-" + id + "-retry" + retryCount;
    }

    @Override
    public String getPartitionColName() {
        return "retry_time";
    }

    @Override
    public java.util.Map<String, Object> getAdditionalJobData() {
        java.util.Map<String, Object> data = new java.util.HashMap<>();
        data.put("phoneNumber", phoneNumber);
        data.put("message", message);
        data.put("retryCount", retryCount);
        data.put("maxRetries", maxRetries);
        data.put("status", status != null ? status : "PENDING");
        if (lastError != null) {
            data.put("lastError", lastError);
        }
        return data;
    }

    public LocalDateTime getRetryTime() {
        return retryTime;
    }

    // Getters and setters
    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Integer getRetryCount() {
        return retryCount;
    }

    public void setRetryCount(Integer retryCount) {
        this.retryCount = retryCount;
    }

    public Integer getMaxRetries() {
        return maxRetries;
    }

    public void setMaxRetries(Integer maxRetries) {
        this.maxRetries = maxRetries;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public LocalDateTime getOriginalScheduledTime() {
        return originalScheduledTime;
    }

    public void setOriginalScheduledTime(LocalDateTime originalScheduledTime) {
        this.originalScheduledTime = originalScheduledTime;
    }

    public String getLastError() {
        return lastError;
    }

    public void setLastError(String lastError) {
        this.lastError = lastError;
    }

    @Override
    public String toString() {
        return "SmsRetryEntity{" +
                "id='" + id + '\'' +
                ", retryTime=" + retryTime +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", message='" + message + '\'' +
                ", retryCount=" + retryCount +
                ", maxRetries=" + maxRetries +
                ", status='" + status + '\'' +
                ", scheduled=" + scheduled +
                '}';
    }
}
