package com.telcobright.scheduler.entity;

import com.telcobright.core.annotation.Column;
import com.telcobright.core.annotation.Id;
import com.telcobright.core.annotation.ShardingKey;
import com.telcobright.core.annotation.Table;
import com.telcobright.core.entity.ShardingEntity;

import java.time.LocalDateTime;

/**
 * Internal entity for storing scheduled jobs in split-verse repository.
 * Jobs are stored as JSON blobs with key columns extracted for querying.
 */
@Table(name = "scheduled_jobs")
public class ScheduledJobEntity implements ShardingEntity<LocalDateTime> {

    @Id(autoGenerated = false)
    @Column(name = "id")
    private String id;

    @ShardingKey
    @Column(name = "scheduled_time")
    private LocalDateTime scheduledTime;

    @Column(name = "job_type")
    private String jobType;

    @Column(name = "job_name")
    private String jobName;

    @Column(name = "job_data_json")
    private String jobDataJson;

    @Column(name = "scheduled")
    private Boolean scheduled;

    public ScheduledJobEntity() {
    }

    public ScheduledJobEntity(String id, LocalDateTime scheduledTime, String jobType,
                              String jobName, String jobDataJson) {
        this.id = id;
        this.scheduledTime = scheduledTime;
        this.jobType = jobType;
        this.jobName = jobName;
        this.jobDataJson = jobDataJson;
        this.scheduled = false;
    }

    @Override
    public String getId() {
        return id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    @Override
    public LocalDateTime getPartitionColValue() {
        return scheduledTime;
    }

    @Override
    public void setPartitionColValue(LocalDateTime scheduledTime) {
        this.scheduledTime = scheduledTime;
    }

    @Override
    public String getPartitionColName() {
        return "scheduled_time";
    }

    public LocalDateTime getScheduledTime() {
        return scheduledTime;
    }

    public void setScheduledTime(LocalDateTime scheduledTime) {
        this.scheduledTime = scheduledTime;
    }

    public String getJobType() {
        return jobType;
    }

    public void setJobType(String jobType) {
        this.jobType = jobType;
    }

    public String getJobName() {
        return jobName;
    }

    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    public String getJobDataJson() {
        return jobDataJson;
    }

    public void setJobDataJson(String jobDataJson) {
        this.jobDataJson = jobDataJson;
    }

    public Boolean getScheduled() {
        return scheduled;
    }

    public void setScheduled(Boolean scheduled) {
        this.scheduled = scheduled;
    }

    @Override
    public String toString() {
        return "ScheduledJobEntity{" +
                "id='" + id + '\'' +
                ", scheduledTime=" + scheduledTime +
                ", jobType='" + jobType + '\'' +
                ", jobName='" + jobName + '\'' +
                ", scheduled=" + scheduled +
                '}';
    }
}
